# ユーザー情報
users:
  userId: auth.uid
  age: string
  area: string
  gender: string
  nickname: string
  position: string
  postCount: int
  # デバイスごとに通知の受け取り設定を変えるとかだと、
  # Map{key: token, value: topic}が良きかも
  topics: list<string>
  # ↑同様、
  # Map{key: token, value: notification}
  notificatioins: list<string>
  createdAt: timestamp
  updatedAt: timestamp

  # 各ユーザーのトークン（隠す予定）: idにはtokenをそのまま使う
  tokens:
    id: token

  # Todo 各ユーザーの機密データ
#  confidential:
#    id: auth.uid
#    email: string

  # 各ユーザーの投稿データ
  posts:
    id: auto
    userId: auth.uid
    age: string
    area: string
    title: string
    body: string
    categories: list<string>
    emotion: string
    gender: string
    nickname: string
    position: string
    replyCount: int
    empathyCount: int
    isReplyExisting: bool
    createdAt: timestamp
    updatedAt: timestamp

    # 各投稿への返信データ
    replies:
      id: auto
      userId: auth.uid
      postId: post.id
      replierId: auth.uid
      age: string
      area: string
      body: string
      gender: string
      nickname: string
      position: string
      createdAt: timestamp
      updatedAt: timestamp

      # 各返信への返信データ
      repliesToReply:
        id: auto
        userId: auth.uid
        postId: post.id
        replyId: reply.id
        replierId: auth.uid
        age: string
        area: string
        body: string
        gender: string
        nickname: string
        position: string
        createdAt: timestamp
        updatedAt: timestamp

  # 各ユーザーのブックマークした投稿
  bookmarkedPosts:
    id: post.id
    userId: auth.id
    createdAt: timestamp

  # 各ユーザーの共感した投稿
  empathizedPosts:
    id: post.id
    userId: auth.id
    myEmpathyCount: int
    createdAt: timestamp

  # 各ユーザーの下書きした投稿
  draftedPosts:
  　id: auto
    userId: auth.uid
    age: string
    area: string
    title: string
    body: string
    categories: list
    emotion: string
    gender: string
    nickname: string
    position: string
    replyCount: int
    empathyCount: int
    isReplyExisting: bool
    createdAt: timestamp
    updatedAt: timestamp

  # 各ユーザーの下書きした投稿への返信
  draftedReplies:
    id: auto
    userId: post.userId
    postId: post.id
    replierId: auth.uid
    age: string
    area: string
    body: string
    gender: string
    nickname: string
    position: string
    createdAt: timestamp
    updatedAt: timestamp

  # 各ユーザーの下書きした返信への返信
  draftedRepliesToReply:
    id: auto
    userId: reply.userId
    postId: reply.postId
    replyId: reply.id
    replierId: auth.uid
    age: string
    area: string
    body: string
    gender: string
    nickname: string
    position: string
    createdAt: timestamp
    updatedAt: timestamp

# お問い合わせ内容
contacts:
  id: auto
  userId: auth.uid
  email: string
  category: string
  content: string
  createdAt: timestamp

