# ユーザー情報
# /users
users:
  userId: auth.uid
  age: string
  area: string
  gender: string
  nickname: string
  position: string
  postCount: int
  # デバイスごとに通知の受け取り設定を変えるとかだと、
  # Map{key: token, value: topic}が良きかも
  topics: list<string>
  # ↑同様、
  # Map{key: token, value: notification}
  notifications: list<string>
  createdAt: timestamp
  updatedAt: timestamp

  # 各ユーザーの投稿データ
  # /users/{userId}/posts
  posts:
    id: auto
    userId: auth.uid
    age: string
    area: string
    title: string
    body: string
    categories: list<string>
    emotion: string
    gender: string
    nickname: string
    position: string
    replyCount: int
    empathyCount: int
    isReplyExisting: bool
    createdAt: timestamp
    updatedAt: timestamp

    # /users/{userId}/posts/{postId}/replies
    # 各投稿への返信データ
    replies:
      id: auto
      userId: auth.uid
      postId: post.id
      replierId: auth.uid
      age: string
      area: string
      body: string
      gender: string
      nickname: string
      position: string
      empathyCount: int
      createdAt: timestamp
      updatedAt: timestamp

      # 各返信への返信データ
      # /users/{userId}/posts/{postId}/replies/{replyId}/repliesToReply
      repliesToReply:
        id: auto
        userId: auth.uid
        postId: post.id
        replyId: reply.id
        replierId: auth.uid
        age: string
        area: string
        body: string
        gender: string
        nickname: string
        position: string
        empathyCount: int
        createdAt: timestamp
        updatedAt: timestamp

  # 各ユーザーのブックマークした投稿
  # /users/{userId}/bookmarkedPosts
  bookmarkedPosts:
    id: post.id
    userId: auth.id
    createdAt: timestamp

  # 各ユーザーの共感した投稿(返信も含む)
  # /users/{userId}/empathizedPosts
  empathizedPosts:
    id: post.id or reply.id or replyToReplyId
    userId: auth.id
    myEmpathyCount: int
    createdAt: timestamp

  # 各ユーザーの下書きした投稿
  # /users/{userId}/draftedPosts
  draftedPosts:
  　id: auto
    userId: auth.uid
    age: string
    area: string
    title: string
    body: string
    categories: list
    emotion: string
    gender: string
    nickname: string
    position: string
    replyCount: int
    empathyCount: int
    isReplyExisting: bool
    createdAt: timestamp
    updatedAt: timestamp

  # 各ユーザーの下書きした投稿への返信
  # /users/{userId}/draftedReplies
  draftedReplies:
    id: auto
    userId: post.userId
    postId: post.id
    replierId: auth.uid
    age: string
    area: string
    body: string
    gender: string
    nickname: string
    position: string
    createdAt: timestamp
    updatedAt: timestamp

  # 各ユーザーの下書きした返信への返信
  # /users/{userId}/draftedRepliesToReply
  draftedRepliesToReply:
    id: auto
    userId: reply.userId
    postId: reply.postId
    replyId: reply.id
    replierId: auth.uid
    age: string
    area: string
    body: string
    gender: string
    nickname: string
    position: string
    createdAt: timestamp
    updatedAt: timestamp

  # 各ユーザーのトークン（隠す予定）: idにはtoken(string)をそのまま使う
  # /users/{userId}/tokens
  tokens:
    id: token

  # 自分への返信のpush通知があった際に追加しよう（新着のpush通知は追加しない）
  # タップしたらそのpostに飛べるようにしよう
  # /users/{userId}/notifications
  notifications(仮):
    id: auto
    userId: auth.uid
    postId: post.id
    replierId:
    title: string
    body: string
    createdAt: timestamp

  # 各ユーザーの機密データ
  # /users/{userId}/tokens
#  confidential:
#    id: auth.uid
#    email: string

# お問い合わせメール
# /mail/{mailId}/
mail:
  userId: auth.uid
  to: email
  message: map
  delivery: map

# お問い合わせ内容
# /contacts
contacts:
  id: auto
  userId: auth.uid
  email: string
  category: string
  content: string
  createdAt: timestamp
